routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Route::prefix('admin')->group(function () {
    Auth::routes();
    Route::group(['middleware' => 'auth'], function (){
        Route::get('/' , 'DashbordController@dashbord');
        Route::resource('product-category','ProductCategoryController');
    });
});



// Route::group(['prefix' => 'product-category'], function () {
//     Route::get('' , 'ProductCategoryController@index');
// });


// product
Route::resource('product' , 'ProductController');
//Doctor Category
Route::resource('doctor-category', 'DoctorCategoryController');
//Doctors
Route::resource('doctor', 'DoctorController');
// Chemist
Route::resource('chemist', 'ChemistController');
// User
Route::resource('user', 'UserController');
// Quiz
Route::resource('quiz', 'QuizController');

Route::get('schedule' , 'SchedulerController@show_scheduler_list');
Route::post('schedule' , 'SchedulerController@save');
Route::get('list' , 'SchedulerController@get_all_schedule');
Route::get('schedule/{id}/edit' , 'SchedulerController@show_edit');
Route::post('schedule-update' , 'SchedulerController@update_schedular');

Route::get('question' , 'QuestionController@show_question_form');
Route::get('all-questions' , 'QuestionController@index');
Route::get('question/{id}/edit' , 'QuestionController@edit');
Route::post('question-update' , 'QuestionController@update_question');
Route::post('question' , 'QuestionController@save');
Auth::routes();

Route::get('/result', 'ResultController@get_result');
Route::get('/home', 'HomeController@index')->name('home');

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $table= "products";
    protected $fillable = [
        'product_category_id',
        'name',
        'description',
        'dose_form',
        'potency_unit',
        'dose',
        'price',
        'image',
        'created_at',
        'updated_at'
    ];

    public function product_category() {
        return $this->belongsTo('App\ProductCategory' , 'product_category_id');
    }
}

app/Http/Controllers/Api/ProductController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Product;
use App\ProductCategory;

class ProductController extends Controller
{
    public function get_products() {
        $products = Product::with('product_category')->get();
        return response()->json([
            'data' => $products
        ]);
    }

    public function get_category_list () {
        $product_cat = ProductCategory::all();
        return response()->json([
            'data' => $product_cat,
        ]);
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Product;
use App\ProductCategory;
use Dotenv\Validator;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::all();
        return view('product.index', compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $product_categories = ProductCategory::all();
        return view('product.create', compact('product_categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // dd($request->hasfile('image'));
        $request->validate([
            'name' => 'required'
        ]);

        $product = new Product();
        $product->name = $request->name;
        $product->product_category_id = $request->product_category;
        $product->dose = $request->dose;
        $product->potency_unit = $request->potency_unit;
        $product->dose_form = $request->dose_form;
        $product->price = $request->price;
        $product->description = $request->description;
        
        if ($request->hasFile('image')) {
            $file = $request->image;
            $filename = $file->getClientOriginalName();
            $image = date('His') . $filename;
            $destination_path = public_path() . '/images/products';
            $file->move($destination_path, $image);
            $product->image = url('/images/products' . '/' . $image);
        }
        
        $product->save();

        return redirect(url('product'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $product_categories = ProductCategory::all();
        $product = Product::where('id' , $id)->first();
        return view('product.edit', compact('product' , 'product_categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // dd($request->all());
        Product::where('id', $id)->update([
            'product_category_id' => $request->product_category,
            'name' => $request->name,
            'dose' => $request->dose,
            'potency_unit' => $request->potency_unit,
            'dose_form' => $request->dose_form,
            'price' => $request->price,
            'description' => $request->description
        ]);

        if ($request->hasFile('image')) {
            $file = $request->image;
            $filename = $file->getClientOriginalName();
            $image = date('His') . $filename;
            $destination_path = public_path() . '/images/products';
            $file->move($destination_path, $image);
            Product::where('id',$id)->update([
                'image' => url('/images/products' . '/' . $image)
            ]);
        }

        return redirect(url('product'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/product/create.blade.php
@extends('layouts.master')
@section('content')
    <section class="content">
        <div class="row">
            <!-- left column -->
            <div class="col-md-12">
            <!-- general form elements -->
                <div class="box box-primary">
                    <div class="box-header with-border">
                    <h3 class="box-title">Add Product</h3>
                    </div>
                    <!-- /.box-header -->
                    <!-- form start -->
                    <form role="form" method="POST" action="{{route('product.store')}}" enctype="multipart/form-data">
                        @csrf
                        <div class="box-body">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="exampleInputEmail1">Product Name</label>
                                            <input type="text" class="form-control" name="name" placeholder="Enter Product Name">
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="exampleInputEmail1">Product Category</label>
                                            <select class="form-control" name="product_category">
                                                @foreach($product_categories as $val)
                                                    <option value="{{$val->id}}">{{$val->name}}</option>
                                                @endforeach
                                            </select>
                                        </div>
                                    </div>
                                </div>
                            </div>


                            <div class="row">
                                <div class="col-md-12">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="exampleInputEmail1">Dose</label>
                                            <input type="text" class="form-control" name="dose" placeholder="Enter Dose">
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="exampleInputEmail1">Potency Unit</label>
                                            <select class="form-control" name="potency_unit">
                                                <option value="MG">MG</option>
                                                <option value="ML">ML</option>                                            
                                            </select>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-12">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="exampleInputEmail1">Dose Form</label>
                                            <select class="form-control" name="dose_form">
                                                <option value="Tablet">Tablet</option>
                                                <option value="Syp">Syp</option>
                                                <option value="Injection">Injection</option> 
                                                <option value="Cream">Cream</option>                                             
                                            </select>
                                        </div>
                                    </div>
                                    
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="exampleInputEmail1">Price</label>
                                            <input type="text" class="form-control" name="price" placeholder="Enter Price">
                                        </div>
                                    </div>
                                </div>
                            </div>


                            <div class="row">
                                <div class="col-md-12">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="exampleInputFile">Image</label>
                                            <input type="file" id="exampleInputFile" name="image">
                                        </div>
                                    </div>
                                    
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label>Description</label>
                                            <textarea class="form-control" rows="2" name="description" placeholder="Enter Description"></textarea>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            
                        </div>
                    <!-- /.box-body -->

                        <div class="box-footer">
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    </form>
                </div>
                <!-- /.box -->

            </div>
        </div>
    </section>
@endsection

resources/views/product/edit.blade.php
@extends('layouts.master')
@section('content')
    <section class="content">
        <div class="row">
            <!-- left column -->
            <div class="col-md-12">
            <!-- general form elements -->
                <div class="box box-primary">
                    <div class="box-header with-border">
                    <h3 class="box-title">Edit Product</h3>
                    </div>
                    <!-- /.box-header -->
                    <!-- form start -->
                    <form role="form" method="POST" action="{{url('product/' . $product->id)}}" enctype="multipart/form-data">
                        @csrf
                        @method('PUT')
                        <div class="box-body">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="exampleInputEmail1">Product Name</label>
                                            <input type="text" class="form-control" name="name" value="{{$product->name}}" placeholder="Enter Product Name">
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="exampleInputEmail1">Product Category</label>
                                            <select class="form-control" name="product_category">
                                                @foreach($product_categories as $val)
                                                    @if($val->id == $product->id)
                                                        <option selected value="{{$val->id}}">{{$val->name}}</option>
                                                    @else
                                                        <option value="{{$val->id}}">{{$val->name}}</option>
                                                    @endif
                                                @endforeach
                                            </select>
                                        </div>
                                    </div>
                                </div>
                            </div>


                            <div class="row">
                                <div class="col-md-12">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="exampleInputEmail1">Dose</label>
                                            <input type="text" class="form-control" name="dose" value="{{$product->dose}}" placeholder="Enter Dose">
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="exampleInputEmail1">Potency Unit</label>
                                            <select class="form-control" name="potency_unit">
                                                <option @if($product->potency_unit == "MG") selected @endif value="MG">MG</option>
                                                <option @if($product->potency_unit == "ML") selected @endif value="ML">ML</option>                                            
                                            </select>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-12">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="exampleInputEmail1">Dose Form</label>
                                            <select class="form-control" name="dose_form">
                                                <option @if($product->dose_form == "Tablet") selected @endif value="Tablet">Tablet</option>
                                                <option @if($product->dose_form == "Syp") selected @endif value="Syp">Syp</option>
                                                <option @if($product->dose_form == "Injection") selected @endif value="Injection">Injection</option> 
                                                <option @if($product->dose_form == "Cream") selected @endif value="Cream">Cream</option>                                             
                                            </select>
                                        </div>
                                    </div>
                                    
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="exampleInputEmail1">Price</label>
                                            <input type="text" class="form-control" name="price" value="{{$product->price}}" placeholder="Enter Price">
                                        </div>
                                    </div>
                                </div>
                            </div>


                            <div class="row">
                                <div class="col-md-12">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="exampleInputFile">Image</label>
                                            <input type="file" id="exampleInputFile" name="image">
                                        </div>
                                        
                                        <div class="row">
                                            <div class="col-sm-2">
                                                <img src="{{$product->image}}" height="80" width="100">
                                            </div>
                                        </div>
                                    </div>
                                    
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label>Description</label>
                                            <textarea class="form-control" rows="2" name="description"  placeholder="Enter Description">{{$product->description}}</textarea>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            
                        </div>
                    <!-- /.box-body -->

                        <div class="box-footer">
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    </form>
                </div>
                <!-- /.box -->

            </div>
        </div>
    </section>
@endsection

resources/views/product/index.blade.php
@extends('layouts.master')
@section('content')
    <section class="content-header">
      <h1>
        Data Tables
        <small>advanced tables</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="#">Tables</a></li>
        <li class="active">Data tables</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-xs-12">

          <div class="box">
            <div class="box-header">
              <h3 class="box-title">Data Table With Full Features</h3>
              <br>
              <br>
              <a href="{{url('product/create')}}"><button  type="button" class="btn btn-primary">Add Product</button></a>
            </div>
            <!-- /.box-header -->
            
            
            <div class="box-body">
              <table id="example1" class="table table-bordered table-striped">
                <thead>
                <tr>
                  <th>name</th>
                  <th>Action</th>
                </tr>
                </thead>
                <tbody>
                @foreach($products as $val)
                <tr>
                  <td width="90%">{{$val->name}}</td>
                  <td width="10%">
                    <a class="btn btn-success" href="{{url('product/'. $val->id . '/edit/')}}"><i class="fa fa-edit"></i></a>
                    <button class="btn btn-danger" data-toggle="modal" data-target="#{{$val->id}}"><i class="fa fa-trash"></i></button>
                  </td>
                </tr>
                @endforeach
              </table>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </section>
@endsection

@section('js')
    <script>
        $(function () {
            $('#example1').DataTable()
        })
    </script>
@endsection