routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Route::prefix('admin')->group(function () {
    Auth::routes();
    Route::group(['middleware' => 'auth'], function (){
        Route::get('/' , 'DashbordController@dashbord');
        Route::resource('product-category','ProductCategoryController');
    });
});



// Route::group(['prefix' => 'product-category'], function () {
//     Route::get('' , 'ProductCategoryController@index');
// });


// product
Route::resource('product' , 'ProductController');
//Doctor Category
Route::resource('doctor-category', 'DoctorCategoryController');
//Doctors
Route::resource('doctor', 'DoctorController');
// Chemist
Route::resource('chemist', 'ChemistController');
// User
Route::resource('user', 'UserController');
// Quiz
Route::resource('quiz', 'QuizController');

Route::get('schedule' , 'SchedulerController@show_scheduler_list');
Route::post('schedule' , 'SchedulerController@save');
Route::get('list' , 'SchedulerController@get_all_schedule');
Route::get('schedule/{id}/edit' , 'SchedulerController@show_edit');
Route::post('schedule-update' , 'SchedulerController@update_schedular');

Route::get('question' , 'QuestionController@show_question_form');
Route::get('all-questions' , 'QuestionController@index');
Route::get('question/{id}/edit' , 'QuestionController@edit');
Route::post('question-update' , 'QuestionController@update_question');
Route::post('question' , 'QuestionController@save');
Auth::routes();

Route::get('/result', 'ResultController@get_result');
Route::get('/home', 'HomeController@index')->name('home');

app/Chemist.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Chemist extends Model
{
    //
}

app/Http/Controllers/Api/ChemistController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Chemist;

class ChemistController extends Controller
{
    public function get_chemist() {
        $chemists = Chemist::all();
        return response()->json([
            'data' => $chemists
        ]);
    }
}

app/Http/Controllers/ChemistController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Chemist;

class ChemistController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $chemists = Chemist::all();
        return view('chemist.index', compact('chemists'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('chemist.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // dd($request->all());
        $chemist = new Chemist();
        $chemist->name = $request->name;
        $chemist->email = $request->email;
        $chemist->phone_no = $request->phone;
        $chemist->gender = $request->gender;
        $chemist->dob = $request->dob;
        $chemist->address = $request->address;

        if ($request->hasFile('image')) {
            $file = $request->image;
            $filename = $file->getClientOriginalName();
            $image = date('His') . $filename;
            $destination_path = public_path() . '/images/chemists';
            $file->move($destination_path, $image);
            $chemist->image = url('/images/chemists' . '/' . $image);
        }
        $chemist->save();

        return redirect(url('chemist'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $chemist = Chemist::where('id', $id)->first();
        return view('chemist.edit', compact('chemist'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = Chemist::where('id', $id)->update([
            'name' => $request->name,
            'email' => $request->email,
            'phone_no' => $request->phone,
            'gender' => $request->gender,
            'dob' => $request->dob,
            'address' => $request->address
        ]);

        if ($request->hasFile('image')) {
            $file = $request->image;
            $filename = $file->getClientOriginalName();
            $image = date('His') . $filename;
            $destination_path = public_path() . '/images/chemists';
            $file->move($destination_path, $image);
            Chemist::where('id',$id)->update([
                'image' => url('/images/chemists' . '/' . $image)
            ]);
        }

        return redirect(url('chemist'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/chemist/create.blade.php
@extends('layouts.master')
@section('content')
    <section class="content">
        <div class="row">
            <!-- left column -->
            <div class="col-md-12">
            <!-- general form elements -->
                <div class="box box-primary">
                    <div class="box-header with-border">
                    <h3 class="box-title">Add Chemist</h3>
                    </div>
                    <!-- /.box-header -->
                    <!-- form start -->
                    <form role="form" method="POST" action="{{route('chemist.store')}}" enctype="multipart/form-data">
                        @csrf
                        <div class="box-body">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="exampleInputEmail1">Name</label>
                                            <input type="text" class="form-control" name="name" placeholder="Enter Name">
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="exampleInputEmail1">Email</label>
                                            <input type="text" class="form-control" name="email" placeholder="Enter Email">
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-12">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="exampleInputEmail1">Phone</label>
                                            <input type="text" class="form-control" name="phone" placeholder="Enter Phone Number">
                                        </div>
                                    </div>
                                    
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="exampleInputEmail1">Gender</label>
                                            <select class="form-control" name="gender">
                                                <option value="">Select</option>
                                                <option value="Male">Male</option>
                                                <option value="Female">Female</option>
                                            </select>
                                        </div>
                                    </div>
                                </div>
                            </div>


                            <div class="row">
                                <div class="col-md-12">
                                    
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label>DOB:</label>

                                            <div class="input-group date">
                                            <div class="input-group-addon">
                                                <i class="fa fa-calendar"></i>
                                            </div>
                                            <input type="text" class="form-control pull-right" name="dob" id="datepicker">
                                            </div>
                                        </div>
                                    </div>

                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label>Address</label>
                                            <textarea class="form-control" rows="2" name="address" placeholder="Enter Address"></textarea>
                                        </div>
                                    </div>
                                </div>
                            </div>


                            <div class="row">
                                <div class="col-md-12">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="exampleInputFile">Image</label>
                                            <input type="file" id="exampleInputFile" name="image">
                                        </div>
                                    </div>
                                    
                                    <div class="col-md-6">
                                        
                                    </div>
                                </div>
                            </div>
                            
                        </div>
                    <!-- /.box-body -->

                        <div class="box-footer">
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    </form>
                </div>
                <!-- /.box -->

            </div>
        </div>
    </section>
@endsection

@section('js')
    <script>
        //Date picker
        $('#datepicker').datepicker({
        autoclose: true
        })
    </script>
@endsection

resources/views/chemist/edit.blade.php
@extends('layouts.master')
@section('content')
    <section class="content">
        <div class="row">
            <!-- left column -->
            <div class="col-md-12">
            <!-- general form elements -->
                <div class="box box-primary">
                    <div class="box-header with-border">
                    <h3 class="box-title">Add Chemist</h3>
                    </div>
                    <!-- /.box-header -->
                    <!-- form start -->
                    <form role="form" method="POST" action="{{url('chemist/' . $chemist->id)}}" enctype="multipart/form-data">
                        @csrf
                        @method('PUT')
                        <div class="box-body">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="exampleInputEmail1">Name</label>
                                            <input type="text" class="form-control" name="name" value="{{$chemist->name}}" placeholder="Enter Name">
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="exampleInputEmail1">Email</label>
                                            <input type="text" class="form-control" name="email" value="{{$chemist->email}}" placeholder="Enter Email">
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-12">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="exampleInputEmail1">Phone</label>
                                            <input type="text" class="form-control" name="phone" value="{{$chemist->phone_no}}" placeholder="Enter Phone Number">
                                        </div>
                                    </div>
                                    
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="exampleInputEmail1">Gender</label>
                                            <select class="form-control" name="gender">
                                                <option value="">Select</option>
                                                <option @if($chemist->gender == "Male") selected @endif value="Male">Male</option>
                                                <option @if($chemist->gender == "Female") selected @endif value="Female">Female</option>
                                            </select>
                                        </div>
                                    </div>
                                </div>
                            </div>


                            <div class="row">
                                <div class="col-md-12">
                                    
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label>DOB:</label>

                                            <div class="input-group date">
                                            <div class="input-group-addon">
                                                <i class="fa fa-calendar"></i>
                                            </div>
                                            <input type="text" class="form-control pull-right" name="dob" value="{{$chemist->dob}}" id="datepicker">
                                            </div>
                                        </div>
                                    </div>

                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label>Address</label>
                                            <textarea class="form-control" rows="2" name="address" placeholder="Enter Address">{{$chemist->address}}</textarea>
                                        </div>
                                    </div>
                                </div>
                            </div>


                            <div class="row">
                                <div class="col-md-12">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="exampleInputFile">Image</label>
                                            <input type="file" id="exampleInputFile" name="image">
                                        </div>

                                        <div class="row">
                                            <div class="col-sm-2">
                                                <img src="{{$chemist->image}}" height="80" width="100">
                                            </div>
                                        </div>
                                    </div>
                                    
                                    <div class="col-md-6">
                                        
                                    </div>
                                </div>
                            </div>
                            
                        </div>
                    <!-- /.box-body -->

                        <div class="box-footer">
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    </form>
                </div>
                <!-- /.box -->

            </div>
        </div>
    </section>
@endsection

@section('js')
    <script>
        //Date picker
        $('#datepicker').datepicker({
        autoclose: true
        })
    </script>
@endsection

resources/views/chemist/index.blade.php
@extends('layouts.master')
@section('content')
    <section class="content-header">
      <h1>
        Chemists
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i>Home</a></li>
        <li class="active" ><a href="#">Chemist</a></li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-xs-12">

          <div class="box">
            <div class="box-header">
              <br>
              <br>
              <a href="{{url('chemist/create')}}"><button  type="button" class="btn btn-primary">Add Chemist</button></a>
            </div>
            <!-- /.box-header -->
            
            
            <div class="box-body">
              <table id="example1" class="table table-bordered table-striped">
                <thead>
                <tr>
                  <th>Name</th>
                  <th>Email</th>
                  <th>Phone #</th>
                  <th>Action</th>
                </tr>
                </thead>
                <tbody>
                @foreach($chemists as $val)
                <tr>
                  <td >{{$val->name}}</td>
                  <td >{{$val->email}}</td>
                  <td >{{$val->phone_no}}</td>
                  <td width="10%">
                    <a class="btn btn-success" href="{{url('chemist/'. $val->id . '/edit/')}}"><i class="fa fa-edit"></i></a>
                    <button class="btn btn-danger" data-toggle="modal" data-target="#{{$val->id}}"><i class="fa fa-trash"></i></button>
                  </td>
                </tr>
                @endforeach
              </table>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </section>
@endsection

@section('js')
    <script>
        $(function () {
            $('#example1').DataTable()
        })
    </script>
@endsection