routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Route::prefix('admin')->group(function () {
    Auth::routes();
    Route::group(['middleware' => 'auth'], function (){
        Route::get('/' , 'DashbordController@dashbord');
        Route::resource('product-category','ProductCategoryController');
    });
});



// Route::group(['prefix' => 'product-category'], function () {
//     Route::get('' , 'ProductCategoryController@index');
// });


// product
Route::resource('product' , 'ProductController');
//Doctor Category
Route::resource('doctor-category', 'DoctorCategoryController');
//Doctors
Route::resource('doctor', 'DoctorController');
// Chemist
Route::resource('chemist', 'ChemistController');
// User
Route::resource('user', 'UserController');
// Quiz
Route::resource('quiz', 'QuizController');

Route::get('schedule' , 'SchedulerController@show_scheduler_list');
Route::post('schedule' , 'SchedulerController@save');
Route::get('list' , 'SchedulerController@get_all_schedule');
Route::get('schedule/{id}/edit' , 'SchedulerController@show_edit');
Route::post('schedule-update' , 'SchedulerController@update_schedular');

Route::get('question' , 'QuestionController@show_question_form');
Route::get('all-questions' , 'QuestionController@index');
Route::get('question/{id}/edit' , 'QuestionController@edit');
Route::post('question-update' , 'QuestionController@update_question');
Route::post('question' , 'QuestionController@save');
Auth::routes();

Route::get('/result', 'ResultController@get_result');
Route::get('/home', 'HomeController@index')->name('home');

app/Quiz.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Quiz extends Model
{
    protected $table = "quiz";
}

app/Http/Controllers/QuizController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Quiz;

class QuizController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $quizs = Quiz::all();
        return view('quiz.index', compact('quizs'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('quiz.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = new Quiz();
        $data->name = $request->name;
        $data->save();

        return redirect(url('quiz'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/quiz/create.blade.php
@extends('layouts.master')
@section('content')
    <section class="content">
        <div class="row">
            <!-- left column -->
            <div class="col-md-12">
            <!-- general form elements -->
                <div class="box box-primary">
                    <div class="box-header with-border">
                    <h3 class="box-title">Add Quiz</h3>
                    </div>
                    <!-- /.box-header -->
                    <!-- form start -->
                    <form role="form" method="POST" action="{{route('quiz.store')}}">
                        @csrf
                        <div class="box-body">
                            <div class="form-group">
                            <label for="exampleInputEmail1">Name</label>
                            <input type="text" class="form-control" name="name" placeholder="Enter Quiz Name">
                            </div>
                        </div>
                    <!-- /.box-body -->

                        <div class="box-footer">
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    </form>
                </div>
                <!-- /.box -->

            </div>
        </div>
    </section>
@endsection

resources/views/quiz/index.blade.php
@extends('layouts.master')
@section('content')
    <section class="content-header">
      <h1>
        Quiz
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Quiz</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-xs-12">

          <div class="box">
            <div class="box-header">
              <h3 class="box-title">Quiz</h3>
              <br>
              <br>
              <a href="{{url('quiz/create')}}"><button  type="button" class="btn btn-primary">Add Quiz</button></a>
            </div>
            <!-- /.box-header -->
            
            
            <div class="box-body">
              <table id="example1" class="table table-bordered table-striped">
                <thead>
                <tr>
                  <th>Name</th>
                  <th>Action</th>
                </tr>
                </thead>
                <tbody>
                @foreach($quizs as $val)
                <tr>
                  <td width="90%">{{$val->name}}</td>
                  <td width="10%">
                    <a class="btn btn-success" href="{{url('quiz/'. $val->id . '/edit/')}}"><i class="fa fa-edit"></i></a>
                  </td>
                </tr>
                @endforeach
              </table>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </section>
@endsection

@section('js')
    <script>
        $(function () {
            $('#example1').DataTable()
        })
    </script>
@endsection